[general]
static=yes
writeprotect=no
autofallthrough=yes

[dialcore]
exten => _X.,1,NoOp(DialCore: channel ${CHANNEL} to ${EXTEN})
 same => n,Stasis(dialcore)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Inbound PSTN: ${EXTEN})
 same => n,Stasis(dialcore,inbound,${EXTEN})
 same => n,Hangup()

[agi-ivr]
exten => s,1,Answer()
 same => n,AGI(agi://localhost:4573)
 same => n,Hangup()
